language: node_js
node_js:
  - "10.11"
dist: trusty
addons:
  chrome: stable
  apt:
    packages:
      - libnss3
env:
  - NODE_ENV=testing
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test:all
  - npm run build
